{% set version = "1.7.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-calibrate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/calibrate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/calibrate/calibrate_{{ version }}.tar.gz
  sha256: 713b09b415c954e1ef5216088acd40621b0546c45afbb8c2c6f118ecb5cd6fa6

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('calibrate')"           # [not win]
    - "\"%R%\" -e \"library('calibrate')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=calibrate
  license: GPL-2
  summary: Package for drawing calibrated scales with tick marks on (non-orthogonal) variable vectors in scatterplots and biplots. Also provides some functions for multivariate analysis such principal coordinate analysis.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: calibrate
# Version: 1.7.5
# Date: 2019-10-01
# Title: Calibration of Scatterplot and Biplot Axes
# Author: Jan Graffelman <jan.graffelman@upc.edu>
# Maintainer: Jan Graffelman <jan.graffelman@upc.edu>
# Depends: R (>= 3.5.0), MASS
# Description: Package for drawing calibrated scales with tick marks on (non-orthogonal) variable vectors in scatterplots and biplots. Also provides some functions for multivariate analysis such principal coordinate analysis.
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2019-10-01 16:35:06 UTC; jangr
# Repository: CRAN
# Date/Publication: 2019-10-01 17:10:02 UTC
