{% set version = "1.7.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-calibrate
  version: {{ version|replace("-", "_") }}

source:
  fn: calibrate_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/calibrate_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/calibrate/calibrate_{{ version }}.tar.gz
  sha256: 33f4f6874f0a979af3ce592ed1105e829d3df1fbf05c6e0cd3829a13b21d82e8

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-mass

  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('calibrate')"  # [not win]
    - "\"%R%\" -e \"library('calibrate')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=calibrate
  license: GPL-2
  summary: 'Package for drawing calibrated scales with tick marks on (non-orthogonal)  variable
    vectors in scatterplots and biplots. '

  license_family: GPL2

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - dpryan79
