travis:
  secure:
    BINSTAR_TOKEN: UU5zfcoWtkmMLkXoXMgKnGBEsb45+2qZ99EvD82zMh33InZdwvE3gA99HCMG7TN+FmMA231dUi2iWXQemAIWtlZ43zvfCD/y1qiFvinqtJlXUtY/eYXRvQt1mito7Yg+WlfZcbFIRGagWERBfUwgVgfoSNyugSlXQxm0qTruwtEQb6WdaGhfr1lrV914LVcciwwrmb1ePfHGYppk0rZ0Yjy4KqLCN+6KgPB5dHKQh469u99CWDGTBm9YiMrVFTRg9ssg15iVzD1JQkDELQkf2zjtfxDZe7w53Duf/kIyg6ceEytKD931hz8fiWGwrzBaYRQlDuwRcoyFxCsyORHrjYvgzWceKBEmcglR7Lo++Tupnx73nxKOIPFDf9k8ui4HTpBfkjFXIZVJOSthqpZPJXWb7N1TRgio/PJ6pwEP9FXhwE2+826Sl2pJNR2Y0i8EOvktnFQaa9Hwb1y9shWcyqSkiiti+zVoyYcLniomfzIlaOMzV5+S7DmDz2cWCvq2D5/5T+G/X2Xj+grWtYfO67eIfRXNix3ztRWLgeFqjxvKi2xWM5q88ikow9ep68+TKxCGtNW5hgzXJExz5LqvnHNzuw5JFAlrjbMnMuTTGbAwOsSmeA6FNJFyIqu2L9OEwRznQGQ9trBqVI6b0KPO0lIaNkrGi1C5wOVIMlNBT1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
